VersionClients
gandalan/idas-client-libs pull request #277
Opened 2023-09-18 09:02 UTC by gdl-koenig

2023-09-18 09:11 UTC, gdl-reif requested changes

2023-09-18 09:11 UTC, gdl-reif commented on Gandalan.IDAS.WebApi.Client/RESTRoutinen.cs
> +                return _versionClients.FirstOrDefault(i => i.Key == version).Value;
use `_versionClients[version]` instead

2023-09-18 09:11 UTC, gdl-reif commented on Gandalan.IDAS.WebApi.Client/RESTRoutinen.cs
> +                if (!_config.AdditionalHeaders.ContainsKey("api-version"))
Cleaner IMO: Clone `_config` into a new instance, and always add the header

2023-09-18 09:56 UTC, gdl-reif requested changes

2023-09-18 09:56 UTC, gdl-reif commented on Gandalan.IDAS.WebApi.Client/BusinessRoutinen/SerienMaterialBerechnenWebRoutinen.cs
>          public async Task<List<MaterialbedarfDTO>> GetOffenerMaterialBedarfv1Async(Guid serieGuid)
Do it vice versa: keep the original method signature to call v1, and use an explicit v2 in the method name for v2 API call

2023-09-18 09:56 UTC, gdl-reif commented on Gandalan.IDAS.WebApi.Client/HttpClientFactory.cs
> +
Properly implement IClonable

2023-09-18 10:14 UTC, gdl-reif commented
@Saibamen can you do a double check please - I would approve now

2023-09-18 13:22 UTC, Saibamen commented on Gandalan.IDAS.WebApi.Client/RESTRoutinen.cs
> +        public async Task<T> GetAsync<T>(string url, JsonSerializerSettings settings = null, string version = null)
Please fix new warnings (`Parameter 'version' has no matching param tag in the XML comment`)

2023-09-18 13:25 UTC, Saibamen requested changes

2023-09-18 13:25 UTC, Saibamen commented on Gandalan.IDAS.WebApi.Client/RESTRoutinen.cs
> +        public async Task<T> PostAsync<T>(string url, object data, JsonSerializerSettings settings = null, string version = null)
Fix new warning

2023-09-18 13:25 UTC, Saibamen commented on Gandalan.IDAS.WebApi.Client/RESTRoutinen.cs
> +        public async Task<T> PutAsync<T>(string url, object data, JsonSerializerSettings settings = null, string version = null)
Fix new warning

2023-09-18 13:25 UTC, Saibamen commented on Gandalan.IDAS.WebApi.Client/RESTRoutinen.cs
> +        public async Task DeleteAsync(string url, string version = null)
Fix new warning

2023-09-18 13:25 UTC, Saibamen commented on Gandalan.IDAS.WebApi.Client/BusinessRoutinen/WebRoutinenBase.cs
> +        public async Task DeleteAsync(string uri, bool skipAuth = false, string version = null)
A lot of not used optional params (`version`)

2023-09-19 08:41 UTC, gdl-reif approved these changes

2023-09-19 09:03 UTC, Saibamen approved these changes

2023-09-19 09:03 UTC, merged